//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektXenon.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektXenon.Shared.Locale.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR ALL.
        /// </summary>
        public static string ActionClearAllText {
            get {
                return ResourceManager.GetString("ActionClearAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY ALL.
        /// </summary>
        public static string ActionPlayAllText {
            get {
                return ResourceManager.GetString("ActionPlayAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHUFFLE.
        /// </summary>
        public static string ActionShuffleText {
            get {
                return ResourceManager.GetString("ActionShuffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string ExplorePageAllTabText {
            get {
                return ResourceManager.GetString("ExplorePageAllTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED.
        /// </summary>
        public static string ExplorePageFeaturedTabText {
            get {
                return ResourceManager.GetString("ExplorePageFeaturedTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explore.
        /// </summary>
        public static string ExplorePageTitle {
            get {
                return ResourceManager.GetString("ExplorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured.
        /// </summary>
        public static string FeaturedPageTitle {
            get {
                return ResourceManager.GetString("FeaturedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED ITEMS.
        /// </summary>
        public static string HomeViewFeaturedItemsText {
            get {
                return ResourceManager.GetString("HomeViewFeaturedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTEN NOW.
        /// </summary>
        public static string HomeViewListenText {
            get {
                return ResourceManager.GetString("HomeViewListenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEMS.
        /// </summary>
        public static string NavMenuItemHintFeatured {
            get {
                return ResourceManager.GetString("NavMenuItemHintFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO MEDIA.
        /// </summary>
        public static string NavMenuItemHintNowPlaying {
            get {
                return ResourceManager.GetString("NavMenuItemHintNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY NAME, ARTIST ETC..
        /// </summary>
        public static string NavMenuItemHintSearch {
            get {
                return ResourceManager.GetString("NavMenuItemHintSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOW.
        /// </summary>
        public static string NowPlayingPageCurrentTabText {
            get {
                return ResourceManager.GetString("NowPlayingPageCurrentTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUEUE.
        /// </summary>
        public static string NowPlayingPageQueueTabText {
            get {
                return ResourceManager.GetString("NowPlayingPageQueueTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingPageTitle {
            get {
                return ResourceManager.GetString("NowPlayingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED CONTENT.
        /// </summary>
        public static string SettingsPagePageSectionFeaturedTitle {
            get {
                return ResourceManager.GetString("SettingsPagePageSectionFeaturedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP LANGUAGE.
        /// </summary>
        public static string SettingsPagePageSectionLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsPagePageSectionLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEME.
        /// </summary>
        public static string SettingsPagePageSectionThemeTitle {
            get {
                return ResourceManager.GetString("SettingsPagePageSectionThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
